In [2]:
import sys
sys.getsizeof(5)

28

In [3]:
import sys
import numpy as np

In [6]:
arr = np.array([9,8,0,6,8])

In [7]:
for i in arr:
    print(i)

9
8
0
6
8


# This is heading 1
## This is heading 2
## This is heading 3
#$\frag{1}{2}$

In [8]:
B = np.array([[[1,2,3],[2,4,7],[6,7,8]]])

In [9]:
B.shape

(1, 3, 3)

In [11]:
B.ndim


3

In [12]:
B.dtype

dtype('int32')

## square matrix


In [19]:
mat = np.array([[4,8,9],[4,7,0],[9,6,3]])

In [20]:
mat

array([[4, 8, 9],
       [4, 7, 0],
       [9, 6, 3]])

mat[0][0]

In [21]:
mat[0]

array([4, 8, 9])

In [22]:
mat[2][2]

3

In [23]:
size = mat.shape

In [24]:
size[0]

3

In [25]:
type(size)

tuple

In [26]:
size

(3, 3)

In [30]:
for i in range(0,size[0]):
	for j in range(0,size[1]):
		print(mat[i][j])

4
8
9
4
7
0
9
6
3


# summary statistics
## generate 100000 data from snd

In [31]:
x = np.random.normal(0,1,10000)

In [32]:
x[:100]

array([-1.02056718, -0.64952375,  0.82222166, -0.7666323 ,  1.78302447,
        0.10546161, -0.68696594,  1.79314052,  0.05296554, -0.12542268,
       -0.55482501, -0.60821833,  1.16660553, -0.83217754, -1.30933337,
        0.24995192, -0.51548564, -0.02083672, -2.94684343,  0.09044991,
        1.79479788,  0.77309537,  1.69076321,  2.30777302, -0.48880718,
        1.0909501 , -0.25316541, -0.38985198,  1.66135604,  1.53996404,
       -0.41443746,  0.03965012,  0.09505248, -1.71234704, -0.98525065,
       -1.48221951, -0.72681112,  0.83710681,  1.91104629,  0.98316351,
       -0.30453256,  1.50787529,  0.17489345,  0.14170111, -0.53777591,
       -0.52207078,  0.15797224,  0.32739734, -1.79757381, -0.14486391,
       -1.30760862, -1.58498057, -0.07145118,  0.32049694, -0.98844588,
       -0.54669159, -0.87613678,  0.98879485,  0.727913  ,  2.17389063,
       -1.85813851,  0.52566614, -0.02371185, -0.57072837,  0.54650686,
        0.22189701, -1.23940056, -0.42705896, -1.12122185, -1.08

In [33]:
x.sum()

60.80202488562541

In [34]:
x.var()

0.997828712466953

In [35]:
x.std()

0.9989137662816311

In [36]:
x.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [37]:
x.describe

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [38]:
x.mean()

0.006080202488562541

In [39]:
X = x.reshape(10,1000)

In [40]:
X.shape

(10, 1000)

In [41]:
sys.getsizeof(X)

128

In [42]:
X.mean()

0.006080202488562541

In [44]:
X.mean(axis=0)

array([-1.55516306e-02,  6.70839518e-02,  2.71681866e-02,  4.40413932e-02,
       -3.07176618e-01, -1.68918271e-01, -1.56429174e-01,  6.56864756e-01,
       -4.05616220e-01,  2.33703177e-03, -1.71888487e-01, -7.57011769e-02,
       -8.23811410e-02, -2.52921400e-02, -4.68700130e-01,  3.67631442e-03,
        6.26656957e-02,  1.40316479e-01, -3.14446583e-01,  2.42337867e-01,
        4.05880872e-01,  2.40569464e-01, -3.70407576e-01,  1.30126964e-02,
       -3.22119530e-01,  1.40972706e-01,  2.84055553e-01, -2.21284016e-01,
        3.92023008e-01,  6.44889207e-01,  2.22474917e-01, -2.22893200e-02,
       -4.02056757e-01, -3.75400204e-01,  6.16153025e-02, -2.06013059e-01,
       -8.62940315e-02, -5.64091965e-02,  6.96298036e-02,  9.41544574e-02,
        5.25085632e-02, -1.80407822e-01, -3.59631112e-02,  6.24088992e-02,
        5.45432571e-01,  1.31939876e-01,  5.32224497e-01,  1.78088911e-01,
       -8.63401334e-01, -4.94415621e-01, -7.20322518e-01,  1.43158177e-01,
        3.04145868e-02, -

In [45]:
X.mean(axis=1)

array([-0.02726824, -0.00844658, -0.0123001 ,  0.00415118,  0.02689457,
       -0.014683  ,  0.03898862,  0.05537174,  0.01186483, -0.013771  ])

In [46]:
x[0].mean()

-1.0205671815614445